import {Inter} from "next/font/google";
import "./globals.css";
import NavIcons from "@/components/NavIcons";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Empowered For Change",
    description: "Generated by Empowered For Change",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="flex flex-col">
            <NavIcons/>
            {children}
            <Footer/>
        </div>
        </body>
        </html>
    );
}
